quiet: true
compact: true
summary-position: top

directory:
  - ./terraform

framework:
  - terraform

download-external-modules: false
evaluate-variables: true

skip-check:
  - CKV_TF_1

mask: []
secrets-scan-file-type: []
block-list-secret-scan: []
