quiet: true
compact: true
summary-position: top

directory:
  - ./terraform

framework:
  - terraform

download-external-modules: true
evaluate-variables: true

skip-check:
  - CKV_TF_1            # Tofu/Terraform lockfile handling
  - CKV_AWS_18          # S3 access logging not required for artifact bucket
  - CKV_AWS_144         # Cross-region replication not required
  - CKV_AWS_145         # KMS-by-default not enforced when kms_key_arn is null
  - CKV_AWS_147         # CMK encryption for CodeBuild not required
  - CKV_AWS_316         # Privileged mode required for Docker builds
  - CKV_AWS_338         # 1-year log retention not required
  - CKV2_AWS_62         # S3 event notifications not required

mask: []
secrets-scan-file-type: []
block-list-secret-scan: []
