---
# ------------------------
# Name: Martini Upload Package Pipeline
# Description: Zips and uploads Martini packages to a Martini Server Runtime.
# Author: Lonti <support@lonti.com>
# ------------------------

version: 0.2

phases:
  pre_build:
    commands:
      - PARAMETER=$(aws ssm get-parameter --name "$PARAMETER_NAME" --with-decryption --query "Parameter.Value" --output text)

      - "missing=0; for var in PARAMETER_NAME BASE_URL ACCESS_TOKEN; do if [ -z \"${!var}\" ]; then echo \"ERROR: $var is missing\"; missing=1; fi; done; if [ \"$missing\" = \"1\" ]; then exit 1; fi"

      - echo "Resolved PARAMETER_NAME=$PARAMETER_NAME"
      - echo "Resolved BASE_URL=$BASE_URL"

  build:
    commands:
      - chmod +x scripts/upload_packages.sh
      - bash scripts/upload_packages.sh

artifacts:
  files:
    - '**/packages.zip'
    - '**/response_body.log'
    - '**/results.log'
  discard-paths: true
