---
# ------------------------
# Name: Martini Build Pipeline for Docker Images
# Description: Builds a Martini Server Runtime Docker Image and pushes it to AWS ECR.
# Author: Lonti <support@lonti.com>
# ------------------------

version: 0.2

phases:
  pre_build:
    commands:
      - PARAMETER=$(aws ssm get-parameter --name "$BUILD_IMAGE_PARAMETER" --with-decryption --query "Parameter.Value" --output text)
      - export MARTINI_VERSION=$(echo "$PARAMETER" | jq -r '.martini_version')

      - "missing=0; for var in BUILD_IMAGE_PARAMETER MARTINI_VERSION ECR_REPO_URI; do if [ -z \"${!var}\" ] || [ \"${!var}\" = \"null\" ]; then echo \"ERROR: $var is missing or empty\"; missing=1; fi; done; if [ \"$missing\" = \"1\" ]; then exit 1; fi"

      - aws ecr get-login-password | docker login --username AWS --password-stdin "$ECR_REPO_URI"

  build:
    commands:
      - echo "Building Docker image for Martini version ${MARTINI_VERSION}..."
      - docker build -f terraform/scripts/Dockerfile --build-arg MARTINI_VERSION="$MARTINI_VERSION" -t mr:"$MARTINI_VERSION" .
      - echo "Tagging image..."
      - docker tag mr:"$MARTINI_VERSION" "$ECR_REPO_URI:$MARTINI_VERSION"

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push "$ECR_REPO_URI:$MARTINI_VERSION"

artifacts:
  files:
    - '**/*'
  discard-paths: true
