formatter: "markdown table"

sections:
  show:
    - inputs

output:
  file: "README.md"
  mode: "inject"
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name

settings:
  anchor: true
  default: true
  description: true
  escape: true
  hide-empty: true
  indent: 2
  required: true
  sensitive: true
  type: true

recursive:
  enabled: false
